// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZgQa0FMzr6FcI_73jO-TFGKwwEJxIQao',
    appId: '1:903668947753:web:2002985bcb3783d83d3538',
    messagingSenderId: '903668947753',
    projectId: 'ostad-flutter-module',
    authDomain: 'ostad-flutter-module.firebaseapp.com',
    storageBucket: 'ostad-flutter-module.firebasestorage.app',
    measurementId: 'G-XCT3HXVQKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwrQQZ36gY6GhHA6EKshLMYS-zvlp91JA',
    appId: '1:903668947753:android:4c0b865c5bb8f32a3d3538',
    messagingSenderId: '903668947753',
    projectId: 'ostad-flutter-module',
    storageBucket: 'ostad-flutter-module.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEDMdhujlAmuUHvibVMXacvr9WYeLY-0w',
    appId: '1:903668947753:ios:d3b4138bf02a328d3d3538',
    messagingSenderId: '903668947753',
    projectId: 'ostad-flutter-module',
    storageBucket: 'ostad-flutter-module.firebasestorage.app',
    iosBundleId: 'com.example.studentTaskManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEDMdhujlAmuUHvibVMXacvr9WYeLY-0w',
    appId: '1:903668947753:ios:d3b4138bf02a328d3d3538',
    messagingSenderId: '903668947753',
    projectId: 'ostad-flutter-module',
    storageBucket: 'ostad-flutter-module.firebasestorage.app',
    iosBundleId: 'com.example.studentTaskManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZgQa0FMzr6FcI_73jO-TFGKwwEJxIQao',
    appId: '1:903668947753:web:0f058349c3cc82133d3538',
    messagingSenderId: '903668947753',
    projectId: 'ostad-flutter-module',
    authDomain: 'ostad-flutter-module.firebaseapp.com',
    storageBucket: 'ostad-flutter-module.firebasestorage.app',
    measurementId: 'G-REMW99WEG1',
  );
}
